services:
  cctv-scraper:
    build: .
    image: cctv-scraper:latest
    container_name: cctv-scraper
    restart: unless-stopped
    extra_hosts:
      - "atcs-dishubkbb.urbanaccess.net:103.151.226.229"
    env_file:
      - .env
    environment:
      CCTV_CONFIG_FILE: /app/cctv_points.csv
      CCTV_OUTPUT_ROOT: /app/dataset
      TZ: Asia/Jakarta
    volumes:
      - ./dataset:/app/dataset
      - ./cctv_points.csv:/app/cctv_points.csv:ro
      - ./secrets:/app/secrets
